# Configurations
title:            Fourier Analysis notes
longtitle:        Fourier Analysis notes
author:           Ofir David
email:            eofirdavid+fourier@gmail.com
description: >
  Learn Fourier Analysis

version:          1.0
gitbook_version:  3.2.3

url:              'https://totallyreal.github.io'
baseurl:          '/Fourier_Notes'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

exclude:
  - _drafts

# TODO: Move collection order to a file in the collection folder
collections:
  Fourier:
    output: true
    permalink: notes/:collection/:path
    order:
      - Fourier Course Information.md
      - Motivation.md
      - Inner product spaces - a reminder.md
      - Orthogonal sets - a reminder.md
      - Infinite Orthonormal basis.md
      - Fourier Series.md
      - Fourier Transform.md
  FourierHebrew:
    output: true
    permalink: notes/:collection/:path
    order:
      - hebrew_motivation.md
      - basic properties.md
      - hebrew_delta_function.md
      - hebrew_plancharel
#  Temp:
#    output: true
#    permalink: /:collection/:path

collections_dir: notes

page_width: 1000px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

extra_css:
  - css/style.css
  - css/general.css
  - css/hebrew.css
  - https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css

sass:
  sass_dir: _sass
  style: compressed

extra_body_js:
  - js/collapsible.js
