::oTheorem::> [{!}theorem] Theorem:`n`n{Backspace 1}{left 1}`n
::oLemma::> [{!}lem] Lemma:`n`n{Backspace 1}{left 1}`n
::oProof::> [{!}proof]- Proof:`n`n{Backspace 1}{left 1}`n
::oCor::> [{!}cor] Corollary:`n`n{Backspace 1}{left 1}`n
::oDef::> [{!}def] Definition:`n`n{Backspace 1}{left 1}`n
::oExa::> [{!}example]- Example:`n`n{Backspace 1}{left 1}`n
::oProb::> [{!}problem] Problem:`n`n{Backspace 1}{left 1}`n
::oClaim::> [{!}claim] Claim:`n`n{Backspace 1}{left 1}`n
::oExc::> [{!}exc] Excercise:`n`n{Backspace 1}{left 1}`n
::oRem::> [{!}remark] Remark:`n`n{Backspace 1}{left 1}`n
::oFig::> [{!}figure] Figure:`n`n{Backspace 1}{left 1}`n
